### ISSUE TITLE
Don't syntax highlight line-by-line

### ISSUE THREAD

**Issue by asmeurer** [emeryberger/scalene#115]
Scalene appears to syntax highlight the output line-by-line. However, correct syntax highlighting requires knowledge of the full file, not just a single line.

The most obvious impact of this is that docstrings are not highlighted correctly, because it does not recognize that the intermediate lines are inside of a string. This could in theory impact other kinds of syntax too. It would be better to syntax highlight the whole file (or function or whatever), then interpolate those lines into the output.

For example:

<img width="1261" alt="Screen Shot 2021-01-25 at 4 22 08 PM" src="https://user-images.githubusercontent.com/71486/105778381-90a59280-5f29-11eb-8ab5-a4013aea7bbb.png">

**Comment by emeryberger** [comment]
Thanks for raising the issue! This now works as expected.

<img width="1056" alt="Screen Shot 2021-01-27 at 12 12 44 PM" src="https://user-images.githubusercontent.com/1612723/106027589-09772c80-6099-11eb-934b-7793d38c8747.png">
