### ISSUE TITLE
Provide a way to give arguments to tested script

### ISSUE THREAD

**Issue by JulienPalard** [emeryberger/scalene#12]
Hi! Looks like a great project, thanks for it! I tested it tonight, and found something that could be enhanced. (Sorry, no PR at the moment, I have to go to sleep now :p).

I may have missed it, but I found no way to pass arguments to the tested script, even `argv[0]` is not given.

For example, given this file:
```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("foo")
print(parser.parse_args())
```

I'd like the ability to run:

```bash
$ python -m scalene the_file.py an_argument
```

Bests.

Currently with just `python -m scalene the_file.py` argparse is whining there's not even an `argv[0]`, and if I try to add `an_argument` scalene complains about the argument not being recognized.

I bet a sane path would be to stick to the cProfile command line arguments:

```
Usage: cProfile.py [-o output_file_path] [-s sort] [-m module | scriptfile] [arg] ...
```

So one can easily jump from a tool to another.

**Comment by thehesiod** [comment]
another problem is that if you just enable the argparser you app will crash:
```python
     parser = argparse.ArgumentParser(description=APPLICATION_NAME)
   File "/usr/local/lib/python3.8/argparse.py", line 1660, in __init__
     prog = _os.path.basename(_sys.argv[0])
 IndexError: list index out of range
```

**Comment by emeryberger** [comment]
Thanks for the reports! I believe the latest commit fixes these issues. Please feel free to reopen if that's not the case.
