### ISSUE TITLE
crash when used on complex project

### ISSUE THREAD

**Issue by thehesiod** [emeryberger/scalene#13]
I had a few threads active, and can't share the code unfortunately.  I think this is the relevant python callstack, let me know what other information I can provide.

This was on amazonlinux:2 docker container, w/ python 3.8.1

```
orchestrator_1  | Fatal Python error: Unreachable C code path reached
orchestrator_1  | Python runtime state: initialized
orchestrator_1  | 
orchestrator_1  | Thread 0x00007fecf6fc0700 (most recent call first):
orchestrator_1  |   File "/pyenv/test/httplib2/__init__.py", line 194 in _build_ssl_context
orchestrator_1  |   File "/pyenv/test/httplib2/__init__.py", line 1238 in __init__
orchestrator_1  |   File "/pyenv/test/httplib2/__init__.py", line 1758 in request
orchestrator_1  |   File "/py/pyenv/venv_run.sh: line 24:    12 Segmentation fault      "$@"
```

**Comment by emeryberger** [comment]
Were you running just CPU profiling, or CPU + memory profiling?

**Comment by thehesiod** [comment]
cpu + memory

**Comment by emeryberger** [comment]
Can you pull and try the latest version? I am pretty sure I know what the cause was (concurrency issue). Thanks!

**Comment by thehesiod** [comment]
will do, thanks!

**Comment by 2008hsk** [comment]
```
2020-01-21 11:33:35.215727: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Segmentation fault: 11
```
Same for me. Pulling didn't solve my problem

**Comment by emeryberger** [comment]
Circling back to this: first, please pull again (just to make sure). If that still doesn't work, can you possibly share your code or a minimal reproducible case? Otherwise, it's basically not possible for me to debug this. Thanks in advance!

**Comment by thehesiod** [comment]
unfortunately I've since given up on threads and switched to async, feel free to close

**Comment by 2008hsk** [comment]
Unfortunately, I also gave up. feel free to close.

**Comment by wookayin** [comment]
Wait, why is it closed? I think this bug is still present.

**Comment by emeryberger** [comment]
If you can give me a case I can use to reproduce, I will look into it, but otherwise, there’s nothing I can do.
