### ISSUE TITLE
Table shows misleading results for Yappi

### ISSUE THREAD

**Issue by sumerc** [emeryberger/scalene#17]
Hi Emery,

I am author of Yappi and I have seen your work by chance. It seems like a nice project. 

I have a simple request if possible: mainpage shows Yappi like 18x slowdown whereas cProfile is 2x, but the real issue is that: Yappi profiles CPU time by default and cProfile profiles Wall time by default. This makes 10x difference since reading HW clocks is an expensive operation and I think to make comparison fair, I would kindly request you to profile the same application(julia_nogil.py) with setting clock_type to wall. Here is the command I used to do that and the results indicate only 2x-2.5x slowdown roughly similar to cProfile(which should be the case). Currently it seems like it is slower even than the `line_profiler` :) 

```bash
> yappi -c wall julia_nopil.py
playground » python julia_nopil.py                                      
Length of x: 1000
Total elements: 1000000
calculate_z_serial_purepython took 19.6705131531 seconds
Total sum of elements (for validation): 33219980
```

Thanks!

**Comment by emeryberger** [comment]
Hi - thanks for your note!

I guess I am not sure what you would like to appear here - I do think it’s reasonable to use the default settings for tools, given that that is the expected common use case. That said, I can include both results. I observe in passing that Scalene uses CPU time. I do wonder why reading the high performance timer (which I assume is nothing but a shim over something like RDTSC) is expensive: it should in principle be far cheaper than a system call to get elapsed virtual time. FWIW Scalene uses virtual (scheduled) elapsed CPU time. Wall clock time is pretty noisy.

**Comment by sumerc** [comment]
Hi,
>I guess I am not sure what you would like to appear here - I do think it’s reasonable to use the default settings for tools, given that that is the expected common use case. That said, I can include both results.

Yes I agree it is reasonable to use default settings, but on this occasion it gives a false impression like Yappi does have 10x overhead compared to cProfile measuring the same thing(but it is not measuring the same thing) :) That is why I kindly asked if it possible to add wall-time results. It would be great if you can include both results, too.

Thank you :)

>I do wonder why reading the high performance timer (which I assume is nothing but a shim over something like RDTSC) is expensive: it should in principle be far cheaper than a system call to get elapsed virtual time. FWIW Scalene uses virtual (scheduled) elapsed CPU time

I remember looking at this problem years ago lurking the Linux kernel for clues. I really do not remember the details, but I remember putting a single `RDTSC` asm instruction instead of using the `clock_gettime` APIs in Linux(which I use in Yappi currently) and it did not change the picture. Just shaking : wall-time retrieval does not go to kernel space most of the time which makes a difference? Not sure. 

I will also be looking over your solution too. Thanks!

**Comment by emeryberger** [comment]
Updated results now up via https://github.com/emeryberger/scalene/commit/a7afa197e5e3183e2ff9ba1e8ed36cd68bb8dce1.
