### ISSUE TITLE
The project is only available from python3.6 because of f-strings

### ISSUE THREAD

**Issue by Equecevi** [emeryberger/scalene#18]
As it uses f-strings that were available after 3.6
print(f"{fname}: % of CPU time = {percent_cpu_time:6.2f}% out of {Scalene.elapsed_time:6.2f}s.", file=out)
line 211 of scalene/scalene.py

**Comment by friday-james** [comment]
I guess it's ok to support from python 3.6 only? But it should be mentioned in README.md .

**Comment by Equecevi** [comment]
Sure, but why nonsupporting a project from python 3.6 only because f-strings? According to the statistics is a good profiler and better than most of them, I don't see the point there.
I don't know if backwards compatibility would be added but I would like to participate if so happens

**Comment by colin-zhou** [comment]
It has restricted version in scalene.py, and I had tried replacing the f-strings expression with the format one running with python3.5, the memory profile part seems not working, malloc and free always catching the same size which resulted in delta mem size = 0.

**Comment by Equecevi** [comment]
Then the project is working only from python3.6?

**Comment by emeryberger** [comment]
Scalene has a runtime warning that it only works for versions >= 3.6 (https://github.com/emeryberger/scalene/blob/master/scalene/scalene.py#L46). I'm happy to put that in the README. That said, I am not wedded to f-strings (though I really like them). @colin-zhou, I see no reason _a priori_ why the memory profiling wouldn't work with _any_ version of Python. Can you share your fork so I can see what's going on? Thanks. (If I can easily support earlier versions of Python, I am happy to do so.)

**Comment by colin-zhou** [comment]
I have fork here: https://github.com/colin-zhou/scalene.git，in the fork repo i added a function doit4, start the testcase with python3.5  and run as "LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc python3 -m scalene test/testme.py", in my option, this should take more than 1000000 * 8 / 1024 / 1024 = 76.3MB，but the testcase alwalys present with 1.0(in line 47)，which i think is not correct.

**Comment by emeryberger** [comment]
I suspect this is a numpy issue, not a Scalene issue. See https://docs.scipy.org/doc/numpy/release.html#support-for-tracemalloc-in-python-3-6.

Please submit your mods to the f-strings as a PR. Thanks!

**Comment by colin-zhou** [comment]
I would like do it.

**Comment by emeryberger** [comment]
Thanks! Also, in fact, it looks like Scalene is just not reporting numpy memory consumption because it wasn't yielding any growth (that is, the `mallocs` and `frees` cancel out). I changed the comments in Scalene to point out this is growth; I wonder about just reporting `mallocs` and `frees` separately: `mallocs` - `frees` = growth, `mallocs` + `frees` = allocation operations. Thoughts?

**Comment by emeryberger** [comment]
Closing since this has been done.
