### ISSUE TITLE
Segfault with CPU+Memory profiling

### ISSUE THREAD

**Issue by groutr** [emeryberger/scalene#24]
Trying out the memory profiler but get a segfault with benchmark/julia1_nopil.py.  I modified the benchmark to run a little longer.  When running the benchmark with no modification, it succeeds.
```
❯ make
clang++ -std=c++14 -g -ffast-math -fno-builtin-malloc -O3 -DNDEBUG  -D'CUSTOM_PREFIX(x)=xx##x' -I/usr/include/nptl -fno-builtin-malloc -pipe -fPIC -I. -I./include -IHeap-Layers -IHeap-Layers/utility -D_REENTRANT=1 -shared libscalene.cpp Heap-Layers/wrappers/gnuwrapper.cpp -Bsymbolic -o libscalene.so -ldl -lpthread
Heap-Layers/wrappers/gnuwrapper.cpp:55:9: warning: 'CUSTOM_PREFIX' macro redefined [-Wmacro-redefined]
#define CUSTOM_PREFIX(x) custom##x
        ^
<command line>:2:9: note: previous definition is here
#define CUSTOM_PREFIX(x) xx##x
        ^
1 warning generated.

~/projects/scalene fix_usage*
❯ LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc python -m scalene benchmarks/julia1_nopil.py
Length of x: 2000
Total elements: 4000000
Scalene: Memory exhausted: sz = 32
[1]    1376452 segmentation fault (core dumped)  LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc python -m scalene
```

Config:
clang version 9.0.1
Target: x86_64-pc-linux-gnu  (archlinux)
Python 3.8.1
scalene master (0ef54675629945be06c0f0582b6c92193629c23f)

**Comment by emeryberger** [comment]
Thanks for the bug report! This has been fixed with https://github.com/emeryberger/scalene/commit/92cbea4cebaa00dd846d803cbc214d2347d497ba.

    % DYLD_INSERT_LIBRARIES=./libscalene.dylib PYTHONMALLOC=malloc python3 -m scalene benchmarks/julia1_nopil.py
    Length of x: 2000
    Total elements: 4000000
    calculate_z_serial_purepython  took 37.322843074798584 seconds
    benchmarks/julia1_nopil.py: % of CPU time = 100.00% out of  39.19s.
      	 | CPU %    | CPU %    | Memory (MB) |
      Line	 | (Python) | (C)      |             | [benchmarks/julia1_nopil.py]
    --------------------------------------------------------------------------------
         1	 |          |          |             | # Pasted from Chapter 2, High Performance Python - O'Reilly Media;
         2	 |          |          |             | # minor modifications for Python 3 by Emery Berger
         3	 |          |          |             | 
         4	 |          |          |             | """Julia set generator without optional PIL-based image drawing"""
         5	 |          |          |             | import time
         6	 |          |          |             | # area of complex space to investigate
         7	 |          |          |             | x1, x2, y1, y2 = -1.8, 1.8, -1.8, 1.8
         8	 |          |          |             | c_real, c_imag = -0.62772, -.42193
         9	 |          |          |             | 
        10	 |          |          |             | #@profile
        11	 |          |          |             | def calculate_z_serial_purepython(maxiter, zs, cs):
        12	 |          |          |             |     """Calculate output list using Julia update rule"""
        13	 |   0.03%  |   0.06%  |      1.00   |     output = [0] * len(zs)
        14	 |   0.30%  |   0.04%  |    119.00   |     for i in range(len(zs)):
        15	 |          |          |             |         n = 0
        16	 |   0.61%  |   0.05%  |   -128.00   |         z = zs[i]
        17	 |   0.35%  |   0.04%  |   -106.00   |         c = cs[i]
        18	 |  23.27%  |   1.75%  |             |         while abs(z) < 2 and n < maxiter:
        19	 |  41.27%  |   3.80%  |   4077.00   |             z = z * z + c
        20	 |  17.90%  |   1.62%  |  -3950.00   |             n += 1
        21	 |   0.15%  |   0.02%  |             |         output[i] = n
        22	 |          |          |             |     return output
        23	 |          |          |             | 
        24	 |          |          |             | 
        25	 |          |          |             | #@profile
        26	 |          |          |             | def calc_pure_python(desired_width, max_iterations):
        27	 |          |          |             |     """Create a list of complex coordinates (zs) and complex
        28	 |          |          |             |     parameters (cs), build Julia set, and display"""
        29	 |          |          |             |     x_step = (float(x2 - x1) / float(desired_width))
        30	 |          |          |             |     y_step = (float(y1 - y2) / float(desired_width))
        31	 |          |          |             |     x = []
        32	 |          |          |             |     y = []
        33	 |          |          |             |     ycoord = y2
        34	 |          |          |             |     while ycoord > y1:
        35	 |          |          |      1.00   |         y.append(ycoord)
        36	 |          |          |             |         ycoord += y_step
        37	 |          |          |             |     xcoord = x1
        38	 |          |          |             |     while xcoord < x2:
        39	 |          |          |             |         x.append(xcoord)
        40	 |          |          |             |         xcoord += x_step
        41	 |          |          |             |     # Build a list of coordinates and the initial condition for each cell.
        42	 |          |          |             |     # Note that our initial condition is a constant and could easily be removed;
        43	 |          |          |             |     # we use it to simulate a real-world scenario with several inputs to
        44	 |          |          |             |     # our function.
        45	 |          |          |             |     zs = []
        46	 |          |          |             |     cs = []
        47	 |          |          |             |     for ycoord in y:
        48	 |   0.03%  |   0.00%  |             |         for xcoord in x:
        49	 |   5.12%  |   0.98%  |     49.00   |             zs.append(complex(xcoord, ycoord))
        50	 |   1.67%  |   0.30%  |    181.00   |             cs.append(complex(c_real, c_imag))
        51	 |          |          |             |     print("Length of x:", len(x))
        52	 |          |          |             |     print("Total elements:", len(zs))
        53	 |          |          |             |     start_time = time.time()
        54	 |          |          |             |     output = calculate_z_serial_purepython(max_iterations, zs, cs)
        55	 |          |          |             |     end_time = time.time()
        56	 |          |          |             |     secs = end_time - start_time
        57	 |          |          |             |     print("calculate_z_serial_purepython " + " took", secs, "seconds")
        58	 |          |          |             | 
        59	 |          |          |             |     # This sum is expected for a 1000^2 grid with 300 iterations.
        60	 |          |          |             |     # It catches minor errors we might introduce when we're
        61	 |          |          |             |     # working on a fixed set of inputs.
        62	 |          |          |             |     ### assert sum(output) == 33219980
        63	 |          |          |             | 
        64	 |          |          |             | 
        65	 |          |          |             | if __name__ == "__main__":
        66	 |          |          |             |     # Calculate the Julia set using a pure Python solution with
        67	 |          |          |             |     # reasonable defaults for a laptop
        68	 |   0.03%  |   0.60%  |     -1.00   |     calc_pure_python(desired_width=2000, max_iterations=300)
        69	 |          |          |             |
