### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by antonalekseev** [emeryberger/scalene#29]
Hi, thanks for the great tool! I created Homebrew [formula](https://github.com/antonalekseev/homebrew-tap/blob/master/libscalene.rb) in order to make installation and usage on macOS more convenient which builds and installs `libscalene.dylib` along with the wrapper script:

``` 
#!/usr/bin/env sh

DYLD_INSERT_LIBRARIES=/usr/local/Cellar/libscalene/HEAD-e3cdcb7/lib/libscalene.dylib PYTHONMALLOC=malloc python -m scalene "$@"
```

Formula can be installed with:

```
$ brew tap antonalekseev/tap
$ brew install --head libscalene
```

and then used as simple as `$ scalene test/testme.py`

If you don't mind it can be placed in this repository in `Formula` directory in order to make it available for tapping with `$ brew tap emeryberger/scalene`, or just mentioned in the `README` with my tap as an installation option.

**Comment by emeryberger** [comment]
Cool! I'd gladly accept a PR for this!

**Comment by emeryberger** [comment]
Never mind, added myself. Thanks!!

**Comment by emeryberger** [comment]
See https://github.com/emeryberger/scalene/commit/ec8cfd9359329af8022a04a52533721d66cd726d
