### ISSUE TITLE
Support `console_scripts`

### ISSUE THREAD

**Issue by jessemyers** [emeryberger/scalene#3]
I tried running `scalene` on one of my CLI programs. It didn't go well:
 - I tried running `python -m scalene --help`; this does not work
 - I generally write my CLI programs to launch `console_scripts` entry points, which doesn't seem supported.
 - I added an explicit `if __name__ == "__main__"` to my CLI program and `scalene` no longer aborted; however it also didn't produce any output beyond what my program already produced.

Any guidance on proper usage would be appreciated.

**Comment by emeryberger** [comment]
I'd love a repro case.

**Comment by pohmelie** [comment]
``` sh
$ python -m scalene --help
scalene: could not find input file.
```
First of all, there are no docs. Secondly, what if I want to profile `console_scripts` or python modules (not files).
Even cProfile have some abilities for this:
```
$ python -m cProfile --help
Usage: cProfile.py [-o output_file_path] [-s sort] [-m module | scriptfile] [arg] ...

Options:
  -h, --help            show this help message and exit
  -o OUTFILE, --outfile=OUTFILE
                        Save stats to <outfile>
  -s SORT, --sort=SORT  Sort order when printing to stdout, based on
                        pstats.Stats class
  -m                    Profile a library module
```

**Comment by emeryberger** [comment]
I'd be happy to add more descriptive text via help (I am planning to add an --outfile option, so the time is right).

Usage is currently just `python -m scalene your-file-goes-here.py`. It doesn't have explicit support for cosole_scripts or modules, but that shouldn't be hard to add. If you have some test cases you could share, that would be helpful.

**Comment by pohmelie** [comment]
`console_scripts` are just plain python files in python `bin` directory without extension with shebang string. This one is for `alembic` library:
```
#!/home/poh/.pyenv/versions/3.7.2/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys

from alembic.config import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
They can be actually runned with `scalene` (did not test output though):
```
$ python -m scalene $(which alembic)
```
or in case of `pyenv`:
```
$ python -m scalene $(pyenv which alembic)
```
But, this is not very elegant.

For modules [`runpy`](https://docs.python.org/3/library/runpy.html?highlight=runpy#module-runpy) should be used.

**Comment by jessemyers** [comment]
@emeryberger, here's an example repo that reproduces the issues I originally reported:

https://github.com/jessemyers/scalene-repro

**Comment by emeryberger** [comment]
Updated to provide conventional command-line help and output redirection.

```
 % python3 -m scalene --help                                   
usage: scalene [-h] [-o OUTFILE] prog

Scalene: a high-precision CPU and memory profiler.
https://github.com/emeryberger/scalene

    for CPU profiling only:
  % python -m scalene yourprogram.py
    for CPU and memory profiling (Mac OS X):
  % DYLD_INSERT_LIBRARIES=$PWD/libscalene.dylib PYTHONMALLOC=malloc python -m scalene yourprogram.py
    for CPU and memory profiling (Linux):
  % LD_PRELOAD=$PWD/libscalene.dylib PYTHONMALLOC=malloc python -m scalene yourprogram.py

positional arguments:
  prog                  program to be profiled

optional arguments:
  -h, --help            show this help message and exit
  -o OUTFILE, --outfile OUTFILE
                        file to hold profiler output (default: stdout)
```

Will work on the other issue described here.

**Comment by Insutanto** [comment]
I have a new pull request for support console_scripts. 😸

**Comment by emeryberger** [comment]
Merged, thanks!
