### ISSUE TITLE
add pip install for the dynamic library for memory profiling

### ISSUE THREAD

**Issue by emeryberger** [emeryberger/scalene#30]
Right now, using scalene's memory profiling feature requires downloading and building from the github repo. It would be nicer and more convenient if this could be done via `pip install`.

**Comment by emeryberger** [comment]
As mentioned, @bpowers

**Comment by emeryberger** [comment]
Note that installation with Homebrew (for Mac OS X) does "the right thing" automatically.

**Comment by Insutanto** [comment]
How can I help in this mission? I am interested in this issue.

**Comment by emeryberger** [comment]
@Insutanto I simply am unclear on what the best way is to go here. Shipping binaries (seems likely to be the easiest)? Trying to build locally? I also don't know what's involved in packaging these things up.

**Comment by Insutanto** [comment]
Some people from China tell me that it is difficult for them to build it locally. Maybe we can use python wheels to distribute the scalene. So, they don't need to build scalene locally.
Many projects use python wheels, such as TensorFlow, PyTorch, so on.

> wheel (in this context) is a project that adds the bdist_wheel command to distutils/setuptools. This produces a cross platform binary packaging format (called “wheels” or “wheel files” and defined in PEP 427) that allows Python libraries, even those including binary extensions, to be installed on a system without needing to be built locally.
from https://docs.python.org/3.6/distributing/index.html

> PyPI currently allows uploading platform-specific wheels for Windows, macOS and Linux. It is useful to create wheels for these platforms, as it avoids the need for your users to compile the package when installing.
from https://pythonwheels.com/

**Comment by Insutanto** [comment]
@emeryberger  Build locally is not very wells to promote the project. I am glades to help improve it. ☺️

**Comment by emeryberger** [comment]
With the latest version, `pip install` now installs the shared libraries (and sets the appropriate environment variables automagically); tested on Ubuntu, x86-64. @Insutanto can you test?

**Comment by Insutanto** [comment]
@emeryberger I am happy to do some tests last night, but I fount some errors.
The first error is `ModuleNotFoundError`, I have created a PR.#59 
Today, I will continue the tests in our production environments.

**Comment by emeryberger** [comment]
Merged, thanks!

**Comment by emeryberger** [comment]
Note that you might see a performance hit because now memory and copy profiling are automatically on by default (via the shared libraries). To disable this behavior, use the command-line flag `--cpu-only`.

**Comment by glaida2020** [comment]
Could you please give a short instruction on how to build scalene on Windows 10 to get the memory profiling? I downloaded the repo, but don't know what commands to call, like: C:\scalene-master> mkdir build, cd build, ... cmake/nmake ...?

**Comment by emeryberger** [comment]
There's no way to do this at the moment, as the memory profiling library does not currently support Windows, for technical reasons (there is in effect built-in support for re-routing memory allocation requests on Linux and Mac, but not on WIndows).
