### ISSUE TITLE
Profiling multiple files

### ISSUE THREAD

**Issue by aosokin** [emeryberger/scalene#37]
Hi, I might be missing smth obvious, but is there an option to profile code from multiple files or at least to choose the file to profile?

Say I have three files.
main.py:
```python
import fast
import slow

def main():
	i = 5000
	s = slow.run(i)
	print(s)
	s = fast.run(i)
	print(s)

if __name__ == "__main__":
    main()
```

slow.py:
```python
def run(i):
    s = 0
    for j in range(i):
        for k in range(j):
            s +=1
    return s
```

fast.py:
```python
def run(i):
    s = i * (i - 1) // 2
    return s
```

When I run `python -m scalene main.py` I get this:
```
slow.py: % of CPU time = 100.00% out of   0.35s.
  	 |     CPU % |     CPU % |   
  Line	 |  (Python) |  (native) |  [slow.py]
--------------------------------------------------------------------------------
     1	 |           |           | def run(i):
     2	 |           |           |     s = 0
     3	 |           |           |     for j in range(i):
     4	 |    11.69% |           |         for k in range(j):
     5	 |    87.68% |     1.80% |             s +=1
     6	 |           |           |     return s
```

Is there a way to profile main.py and fast.py as well as slow.py?

**Comment by emeryberger** [comment]
There was an accidentally introduced indentation error! Fixed. Please pull again / pip install --U. I just ran your code, but `main.py` and `fast py` are so fast that they almost never get any samples.

**Comment by aosokin** [comment]
Great, thanks a lot for such a quick reaction!
