### ISSUE TITLE
make error of Heap-Layers

### ISSUE THREAD

**Issue by zhuohoudeputao** [emeryberger/scalene#47]
Heap-Layers/wrappers/gnuwrapper.cpp:55:9: warning: 'CUSTOM_PREFIX' macro redefined
      [-Wmacro-redefined]
#define CUSTOM_PREFIX(x) custom##x
        ^
<command line>:2:9: note: previous definition is here
#define CUSTOM_PREFIX(x) xx##x
        ^
1 warning generated.

**Comment by emeryberger** [comment]
It's just a warning and can be ignored.

**Comment by emeryberger** [comment]
In any event, I have now suppressed that warning, so if you pull from Heap-Layers again, it should not appear.
