### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by zhuohoudeputao** [emeryberger/scalene#48]
[1]    4103 segmentation fault  LD_PRELOAD=$PWD/libscalene.so PYTHONMALLOC=malloc scalene test/testme.py

**Comment by emeryberger** [comment]
What system? Please provide as many details as possible so I can reproduce the error.

**Comment by zhuohoudeputao** [comment]
Ubuntu on wsl2

**Comment by zhuohoudeputao** [comment]
I install clang by
sudo apt install clang
and then
git clone scalene
make
all work well now
but it fails to run memory profile

**Comment by emeryberger** [comment]
What command line are you using?

**Comment by emeryberger** [comment]
Also, what did you do differently to get it to work well?

**Comment by emeryberger** [comment]
I have built and successfully tested scalene on WSL2 (Ubuntu 20), though I made some fixes. I recommend you pull the latest version. Everything now works fine on my end (with `LD_PRELOAD=./libscalene.so PYTHONMALLOC=malloc python3 -m scalene test/testme.py`). Please confirm - thanks.

**Comment by zhuohoudeputao** [comment]
It works now! Thank you very much!
