### ISSUE TITLE
make failed with commit hash 40b21441cd42d95b9123d4d2dbf230161e0b3ba9

### ISSUE THREAD

**Issue by wxkdesky** [emeryberger/scalene#49]
I met with make errors(link errors) when using the lastest code
commit 40b21441cd42d95b9123d4d2dbf230161e0b3ba9
Author: emeryberger <emery.berger@gmail.com>
Date:   Sun Apr 26 13:35:12 2020 -0400

    Added fast memcpy implementation.

The error message is about llvmgolden.so
Linking failed because this llvm plug in is not installed.
My workaround is to change heaplayers-make.mk in the first line
from: CPPFLAGS = -std=c++17 -flto -g -ffast-math ......
to    : CPPFLAGS = -std=c++17 -g -ffast-math ......

remove -flto

**Comment by emeryberger** [comment]
That is very strange indeed. What platform is this on?

**Comment by emeryberger** [comment]
bump @wxkdesky

**Comment by wxkdesky** [comment]
Hi My system is ubuntu14,04
And I installed clang with llvm(9.0) using anaconda.

**Comment by emeryberger** [comment]
OK. 14.04 a 6 year old release of Ubuntu and I am not going to support it, but people who search for this can find the issue. Thanks for the report.
