### ISSUE TITLE
pprofile style context profiling

### ISSUE THREAD

**Issue by spott** [emeryberger/scalene#5]
I'm usually not interested in profiling an entire program, I'm more interested in profiling some hotspot of code, or just some new piece of code.

pprofile allows for just profiling a specific region of code (from pprofile's main page):

```
def someOtherHotSpotCallable():
    # Statistic profiler
    prof = pprofile.StatisticalProfile()
    with prof(
        period=0.001, # Sample every 1ms
        single=True, # Only sample current thread
    ):
        # Code to profile
    prof.print_stats()
```

It would be nice if scalene allowed for such granularity.

**Comment by chiragjn** [comment]
+1, I would also like this

I tried doing this when scalene was first announced
https://github.com/emeryberger/scalene/compare/master...chiragjn:contextmanager_patch
Since scalene does line by line output. it would output too much code or crash with ipython cells (because they are not files).

My fork is also out of date by now, I might sync up and give it another shot if I get some time

**Comment by emeryberger** [comment]
So, did this patch work? It doesn't look like it would take much effort to resolve the conflicts (I can do this, just let me know).

**Comment by johanvergeer** [comment]
@emeryberger Since this hasn't been updated, and I would like to have a context manager for my project, I would like to pick this one up.

**Comment by emeryberger** [comment]
Sounds great! I look forward to a PR. Let me know if you have any questions, etc.

**Comment by johanvergeer** [comment]
It seems to be harder than I initially thought. Would you be willing to call some time so we can discuss a good approach to solve this?

**Comment by emeryberger** [comment]
Sure. Drop me a line: emery.berger@gmail.com.

I do think that it doesn't make sense to disable a lot of the functionality; in effect, it seems like the contextmanager approach should just be a way to say "just give me the results from this function"; that maybe is most expediently handled in the `should_trace` method, and then with some additional logic in the profile output routine.

**Comment by indigoviolet** [comment]
was there any progress on this? one reason for wanting it is to leave out startup overhead from the profile (ie. if I know that the startup overhead is paid only once or not in the perf-intensive part of my code)

**Comment by emeryberger** [comment]
It would be straightforward to have a command-line parameter for a start profile delay, but I am not clear how much it would matter for any sufficiently long running program, which would eventually amortize the startup cost. But if it’s a real need, it would be easy to add.

**Comment by indigoviolet** [comment]
sorry I wasn't clear earlier. I meant that in my program, there is an expensive data loading step at the beginning that needs to be executed once, and then a loop over less expensive steps. I want to profile the less expensive step. I'd like to skip profiling the data loading step.

**Comment by emeryberger** [comment]
So would it be practical to time the expensive data loading part, and then have Scalene start its profiling after that much time has elapsed?

**Comment by indigoviolet** [comment]
Yes, that is certainly one approach,  but the approach suggested in this issue (a context manager or other way of turning profiling on and off programmatically instead of at the command line) would be my preference - seems cleaner and more flexible.

**Comment by emeryberger** [comment]
From an implementation perspective, it's challenging. Scalene (when it's not invoked with `--cpu-only`) uses a library that replaces all memory operations (allocations, frees, and copying). It's not something you can safely turn and off. What I would actually have to do is profile all the time, but simply discard profiling information when profiling is "off". Since even this would require refactoring and special casing (what happens with multiple processes, for example?), I'd really like to see a compelling case that isn't handled by something much simpler, like delaying the start of profiling.

**Comment by emeryberger** [comment]
UPDATE: As of version 1.1.5, Scalene now supports `@profile` decorators.

**Comment by ClemensA4t1qbit** [comment]
> UPDATE: As of version 1.1.5, Scalene now supports `@profile` decorators.

That's a great feature but I can't seem to figure out how it's used. I have a little test script where the code to profile is in a function decorated with `@profile`. But running scalene still produces the full program's profile. Is there a command line argument I need to pass? If so, it doesn't seem to be mentioned when running `scalene --help`

**Comment by emeryberger** [comment]
It should "just work"; I just tested it on a short script and it behaved as expected (no command-line parameters needed). Can you attach the script?

**Comment by ClemensA4t1qbit** [comment]
My bad; I used `from scalene import profile`, but the trick is to, as you say, just use `@profile`. I was just a bit confused because my IDE complained that in that case `profile` isn't defined anywhere.

I changed it (removed my import) and it does seem to work.

**Comment by emeryberger** [comment]
Great! I'm going to close this issue because I think it's easy enough to use `@profile` instead of context managers and it satisfies the same need, AFAICT.
