### ISSUE TITLE
Strange behavior if script is in a subdirectory

### ISSUE THREAD

**Issue by mwichmann** [emeryberger/scalene#50]
Trying this on a project which has a runner script which tries to find an "engine" (essentially a module) in various different places to support both running from an installed location and from inside the source tree for development. scalene is doing something odd behind the scenes which breaks this project's logic. Quick example to illustrate:

`scripts/foo.py`:
```
import os

print(__file__)
print(os.path.realpath(__file__))
```
Results:
```
$ python3 scripts/foo.py
scripts/foo.py
/tmp/scripts/foo.py   # <- as expected
$ python3 -m scalene scripts/foo.py
scripts/foo.py
/tmp/scripts/scripts/foo.py  # <- the extra /scripts is problematic
```

**Comment by emeryberger** [comment]
Thanks for the report! Just committed a fix - please pull again (or `pip install scalene -U`) to confirm that this fixes it.

**Comment by mwichmann** [comment]
It does fix the example described, thanks!  (I still can't run it on my project though, so there's something else going on, will investigate later)

**Comment by emeryberger** [comment]
Ok, sounds good - please let me know if you track down the issue or narrow it down to something I can test.
