### ISSUE TITLE
Installation: Added AUR package

### ISSUE THREAD

**Issue by wbthomason** [emeryberger/scalene#54]
Just so you're aware, I created this AUR package https://aur.archlinux.org/packages/python-scalene-git/ for installation on Arch Linux/Arch-based Linux distributions.

**Comment by emeryberger** [comment]
Thanks! I'd appreciate a pull request for `README.md` to provide installation instructions for ArchLinux.

**Comment by wbthomason** [comment]
Done! I also realized the `PKGBUILD` didn't install `libscalene.so`, so I've fixed that. Is it correct that if I'm installing that (to `/usr/lib`) and running `setup.py install` (with an appropriate `--root`), I'm installing everything Scalene needs? (just to make sure I didn't miss anything else)

**Comment by emeryberger** [comment]
Yes, that should do it - thanks!
