### ISSUE TITLE
Minimum execution time?

### ISSUE THREAD

**Issue by DavidC0rtes** [emeryberger/scalene#56]
Hello, i'm trying to profile a script, but when calling `python3 scalene script.py` it says "Program did not run for long enough to profile." Unix's time command says it runs for roughly ~96ms ,so my question is What is the minimum time a program must run before it can be profiled by scalene? Or maybe i'm doing something wrong? Thanks

**Comment by emeryberger** [comment]
Currently, Scalene needs code to run for _at least_ 1/100th of a second, and that time has to be spent in your code (and not in Python internals, say) in order to get counted. Can you share your script?

**Comment by emeryberger** [comment]
bump @DavidC0rtes

**Comment by DavidC0rtes** [comment]
Hi, sorry for the delay, well i can share it but it is a little messy (three files and its input is a text file) i just tested it with a very big input which takes roughly 0.2 seconds and no issues.
Type
`./run.py <input-file>
`
The output will be weird and in spanish, sorry!
[files.zip](https://github.com/emeryberger/scalene/files/4678094/files.zip)

**Comment by emeryberger** [comment]
Ya, me alegro de que funcione :).
