### ISSUE TITLE
Scalene changes to directory of program being profiled

### ISSUE THREAD

**Issue by VictorYing** [emeryberger/scalene#60]
Thanks for releasing this tool!

I was trying to profile a program that happened to do a little bit of file I/O, accessing files relative to the current working directory, and spent a couple minutes being confused why the program just died (without printing out any error messages!) when profiled with Scalene before giving up.

Returning to this now, I was able to profile my program if I modify my program to always operate on absolute file paths instead of relative ones. I'm guessing the issue is because Scalene moves into the directory of the program being profiled here, before running the program:
https://github.com/emeryberger/scalene/blob/7d059652614c91baddb9f0f33f2747a07518c364/scalene/scalene.py#L926
It appears that when the program fails to find a file to open while being profiled, the error is silent, which made it hard for me to initially guess what the problem was.

Is it possible to avoid the change of working directory, or at least add some documentation warning about this?

**Comment by emeryberger** [comment]
To be honest, there probably is no reason to keep this behavior. I'm happy to remove it. (It was originally there to simplify development.) My only concern is changing it might disrupt someone's workflow, but I will go ahead and change it and push a new release.

**Comment by emeryberger** [comment]
Closed with https://github.com/emeryberger/scalene/commit/2e4f7527f0bf254d75a830b3785c08256bfdc74a
