### ISSUE TITLE
Problem running scalene with argparse

### ISSUE THREAD

**Issue by joshfactorial** [emeryberger/scalene#64]
I have a program that uses argparse to allow for arguments into the program. Anyway, I tried using scalene a couple different ways but it seems to just hang. Is there a way to get this to work?

example:

```scalene /path/to/python_program.py -r /path/to/input1 -o /path/to/output --extra-flag```

I tried the above after making the program executable (in linux). I also tried:

```scalene python /path/to/python_program.py -r /path/to/input1 -o /path/to/output --extra-flag```

**Comment by emeryberger** [comment]
I'd be happy to test a small example...

**Comment by joshfactorial** [comment]
Okay, well the program I'm trying to profile is in the NEAT genreads package (https://github.com/zstephens/neat-genreads). The exact program I'm trying to profile is in utilities and called gen_mut_model.py, but this one is a simpler one: https://github.com/zstephens/neat-genreads/blob/python3_conversion/utilities/compute_fraglen.py

If I run it like so with the attached input:

`python ~/neat-genreads/utilities/compute_fraglen.py -i /mnt/c/Users/joshf/Documents/work_stuff/neat_data/baby.sam -o test`

it runs fin. If I try to add scalene before it, then I just get nothing.

[baby.zip](https://github.com/emeryberger/scalene/files/4848005/baby.zip)

**Comment by emeryberger** [comment]
The problem appears to be that Scalene was consuming the `-o` argument. I've now changed Scalene to only use `--outfile`, which should reduce the risk of conflicts. I just committed a new version and it's up on `pip`, successfully tested under Linux and Mac OS X. Just run `python3 -m pip install -U scalene`, and let me know if you encounter any other issues.

(I will probably change the argument scheme to consume only arguments up to `---`, if that's there, just so people can avoid any conflicts.)

**Comment by emeryberger** [comment]
Actually, turns out you can just use `--` already, as in `scalene yourprog.py -- (your args go here)`.

**Comment by emeryberger** [comment]
is this working for you now, @joshfactorial ?

**Comment by emeryberger** [comment]
Closing as this works for me on both Linux and Mac.
