### ISSUE TITLE
Scalene decorator

### ISSUE THREAD

**Issue by johanvergeer** [emeryberger/scalene#71]
**Is your feature request related to a problem? Please describe.**

At this moment we can only run Scalene on the entire application, which makes profiling a time consuming process. It would be nice to have more fine-grained control over the functionality that should be profiled.

**Describe the solution you'd like**

Create a decorator that can be used to activate the profiler for specific functions / classes.

```python
@scalene
def func_under_test():
    ...
```

Next create an environment variable that contains a list with all the functions that should be profiled

```sh
SCALENE_PROFILE_FUNCTIONS=func_under_test,another_func_under_test
```

**Describe alternatives you've considered**
Write a separate script that can be run specific functionality.

**Comment by emeryberger** [comment]
Clarification: when you say “time-consuming”, do you mean profiling time, or the time to go through the generated profiles because there are too many files, or...?

**Comment by johanvergeer** [comment]
It would be nice if we can focus on a single piece of functionality in our application at a given time. When we profile the entire application this comes with a (small) overhead of the profiler, but the most time will be in going trought all the output to figure out where the output is for the function that you're looking for.

Also, we have some functions we know will take a lot of memory, but there is not much we can do about those at this moment. Therefore we want to focus on the functions that we do have control over. The nice thing about Scalene is that it filters out modules that do not have a high strain on the system, but some of the functions that are filtered out are exactly the ones that we want to profile.

**Comment by emeryberger** [comment]
This is not entirely what you are looking for, but the latest release of Scalene (just pushed to `pip`, version 1.1) now has a command-line flag `--reduced-profile` which only outputs lines with non-zero profiles. For large files, this *drastically* reduces the output (from potentially thousands of lines to dozens).

Below is an example of a reduced profile.

I think this is a nice, general approach. It has the advantage of not requiring code modification or knowledge _a priori_ of which functions need to be profiled, while not swamping the user with too much output. Let me know what you think!

           /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/selectors.py: % of time =  31.43% out of  10.04s.        
           ╷       ╷       ╷     ╷                                                                                                  
      Line │Time % │Time % │Sys  │                                                                                                  
           │Python │native │%    │/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/selectors.py                      
    ╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
       ... │       │       │     │                                                                                                  
       558 │ 27%   │  4%   │ 31% │                kev_list = self._selector.control(None, max_ev, timeout)                          
       ... │       │       │     │                                                                                                  
           ╵       ╵       ╵     ╵                                                                                                  
        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py: % of time =  23.22% out of  10.04s.    
           ╷       ╷       ╷     ╷                                                                                                  
      Line │Time % │Time % │Sys  │                                                                                                  
           │Python │native │%    │/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py               
    ╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
       ... │       │       │     │                                                                                                  
      1084 │ 20%   │  3%   │ 23% │            stream.write(msg + self.terminator)                                                   
       ... │       │       │     │                                                                                                  
           ╵       ╵       ╵     ╵                                                                                                  
        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/attr/_make.py: % of time =  19.25% out of    
                                                                10.04s.                                                            
           ╷       ╷       ╷    ╷                                                                                                  
      Line │Time % │Time % │Sys │                                                                                                  
           │Python │native │%   │/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/attr/_make.py       
    ╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
       ... │       │       │    │                                                                                                  
         4 │  7%   │  2%   │    │import hashlib                                                                                    
       ... │       │       │    │                                                                                                  
      1119 │  8%   │  2%   │    │    bytecode = compile(script, unique_filename, "exec")                                           
       ... │       │       │    │                                                                                                  
           ╵       ╵       ╵    ╵

**Comment by emeryberger** [comment]
Bump @johanvergeer

**Comment by johanvergeer** [comment]
Sorry Emery. I lost my focus a bit. 

At this moment we solved our case with Memory Profiler (which is slow indeed), but allows us to focus the profiler on a single function.

**Comment by emeryberger** [comment]
No worries - it'd be great if you could check if this modification would have solved your problem, or if there really still is a need for the decorator route. Thanks!

**Comment by Samira-El** [comment]
Hey @emeryberger, on a similar note to the decorator, any plans to make it possible to run Scalene programmatically from within the code like [cProfile](https://docs.python.org/3/library/profile.html#module-cProfile).

**Comment by johanvergeer** [comment]
Hi Emery,

I ran Scalene with the reduce output flag, but that didn't help in our use case. 
We would really like to be able to laser focus on some items in our code. That is what we use the memory profiler decorator for now. 

The only downside is that we have to watch out so we don't do a commit with the decorator,  but we solved that with a custom pre-commit hook. 😄 

Another ben benefit of using the decorator is that we don't lose performance where we don't have to measure.

**Comment by rsudarson** [comment]
Please add support for decorator, some of the user development workflow will be on jupyterlab

**Comment by emeryberger** [comment]
UPDATE: As of version 1.1.5, Scalene now supports `@profile` decorators.

**Comment by emeryberger** [comment]
While this is not the requested `@scalene` operator, it fits with established practice by other profilers, and I think addresses this issue. Please feel free to re-open if not!
