### ISSUE TITLE
"IndexError: list index out of range" if no args given

### ISSUE THREAD

**Issue by Smankusors** [emeryberger/scalene#73]
**Describe the bug**
Ehm... Sorry but, it's kinda funny when user try to launch without any argument, and it shows this instead

```
Scalene failed to initialize.
Traceback (most recent call last):
  File "/home/smankusors/.local/lib/python3.6/site-packages/scalene/scalene.py", line 1462, in main
    with open(sys.argv[0], "rb") as prog_being_profiled:
IndexError: list index out of range
```

**To Reproduce**
1. Just execute `scalene` or `python -m pip scalene` without any arguments

**Expected behavior**
It should be.... show the help message, or tell people to use `-h` or `--help` to show help message?

**Additional context**
I could do PR if you want, I will do `parser.print_help()` if there's no argument given. ([Ref](https://stackoverflow.com/questions/4042452/display-help-message-with-python-argparse-when-script-is-called-without-any-argu/4042861))

**Comment by emeryberger** [comment]
Thanks!

Fixed with https://github.com/emeryberger/scalene/commit/2c159e1462e6274e241a2cbd6db089ae1360e130; released as 1.1.1.
