### ISSUE TITLE
no-op scalene v1.1.1 installation because of packaging mistake (scalene/Adaptive.py should be scalene/adaptive.py)

### ISSUE THREAD

**Issue by boegel** [emeryberger/scalene#76]
The source tarball for `scalene` v1.1.1 available on PyPI contains `scalene/Adaptive.py` rather than `scalene/adaptive.py`, which results in a broken installation because the `from scalene.adaptive import Adaptive` done in `scalene/scalene.py` fails.

It took me a while to figure this out because: i) there are no errors during the installation, and ii) the `scalene` command "works" in the sense that it doesn't produce any errors or warnings, and exits with exit code 0, albeit without producing any output no matter which arguments/options are passed (even `scalene --help` comes back blank); see also #75 .

I had to run this before installation `scalene` from source using `pip install .`:

```
mv scalene/Adaptive.py scalene/adaptive.py
```

I was hitting the issue in macOS with a *case-sensitive* filesystem (which is not the default).
Perhaps the scalene v1.1.1 source package was produced on an OS with a case-insensitive filesystem?

**Comment by emeryberger** [comment]
Nasty error and great catch! Fixed with https://github.com/emeryberger/scalene/commit/28bbceb49b8d478625d5a06fd71c0a8fcd168756 (not even sure how it got in there, but you are correct, I am building this on a case-insensitive filesystem); will push a new version to PyPi shortly.
