### ISSUE TITLE
Support for PPC64le?

### ISSUE THREAD

**Issue by rmchurch** [emeryberger/scalene#86]
**Is your feature request related to a problem? Please describe.**
Trying to memory profile on a Power9 cluster, was excited to try scalene. But right away got the message: 
`scalene warning: currently only 64-bit x86-64 platforms are supported for memory and copy profiling.` Are there any plans to support PPC64le?

**Comment by emeryberger** [comment]
There's no deep reason for not supporting Power9 except that I have no access to a system where I can build the libraries. I thought perhaps IBM Cloud would be an option but it doesn't seem to be... if you happen to know of a place where I can get an account on a system with this architecture, I'd be happy to try it.
